name: Windows MSVC

on:
  push:
    paths:
      - 'src/**'
      - 'res/**'
      - '.github/workflows/windows-msvc.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'res/**'
      - '.github/workflows/windows-msvc.yml'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: windows-2019
    env:
      targetName: bilibili-live-danmuku.exe
      qt_ver: 6.8.1
      qt_arch: win64_msvc2019_64
      msvc_arch: x64

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_ver }}
          arch: ${{ env.qt_arch }}
          modules: qtwebsockets
          cache: true

      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ env.msvc_arch }}

      - name: Configure CMake
        run: >
          cmake
          -B ./build
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: package
        id: package
        env:
          archiveName: ${{ env.qt_arch }}
          msvcArch: ${{ env.msvc_arch }}
        shell: pwsh
        run: |
          & ./scripts/windows-msvc-package.ps1 ${env:archiveName} ${env:targetName}
           $name = ${env:archiveName}
           echo "::set-output name=packageName::$name"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ./build/${{ steps.package.outputs.packageName }}
